name: "PR checks"
on:
  pull_request:
jobs:
  test_lint_and_build:
    name: "Lint sources and check build artifacts"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: npm ci && npm run lint && npm run format-check
      - run: npm run build && npm run pack && git diff --exit-code
